version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: mart_reports
      MYSQL_USER: akira
      MYSQL_PASSWORD: 12345678
    ports:
      - "3308:3306"
  
  admin:    
    image: adminer    
    ports:      
      - "8080:8080"